### ISSUE TITLE
Where can I find documentation for this repo!

### ISSUE THREAD

**Issue by minesh1291** [ivanamihalek/CG#1]
It seems that you have done nice work here. But it's hard for me to use it without documentation.
Thanks.

**Comment by ivanamihalek** [comment]
Hi Minesh,

Welcome to my scratchpad. I would hesitate to call this nice, but you are welcome to help yourself.  It is work in progress and does not have documentation yet. 

You might find a first couple of scripts in both tcga and icgc useful to download and organize data. After that it is just a mess. Let me know if you'd like to work on turning it into a  package :)

**Comment by ivanamihalek** [comment]
Marking the first anniversary of this issue by announcing the [initial release](https://github.com/dogmaticcentral/CG/releases) of the code. Now documented in  [readme](https://github.com/dogmaticcentral/CG), with some minor pointers in the [wiki](https://github.com/dogmaticcentral/CG/wiki). The accompanying manuscript is under review, hope to have the link in the next couple of months.
